[package]
name = "vec-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
ecow = "0.2.3"
rand = "0.9.0"
smallvec = "1.14.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "vector_bench"
harness = false
